### ISSUE TITLE
Livewire support

### ISSUE THREAD

**Issue by dennisvandalen** [pascalbaljetmedia/laravel-form-components#2]
Thanks for this library, saves me a lot of time.

I noticed when I'm using Livewire the errors don't show. It's because in Livewire the errors are not in the session, so [this line](https://github.com/pascalbaljetmedia/laravel-form-components/blob/f037af01586c0e903c498adbf4a060ff850d138a/src/Components/HandlesValidationErrors.php#L35) always returns an empty bag.

I also noticed that the check for hasError is not that usefull because in the layouts it's always wrapped in the `@error` directive. [Like form-errors.blade.php](https://github.com/pascalbaljetmedia/laravel-form-components/blob/f037af01586c0e903c498adbf4a060ff850d138a/resources/views/tailwind/form-errors.blade.php)

Maybe just get rid of the `hasError` part and just use the `showError`, it should be compatible with Livewire that way and you don't double check for errors.

What's your opinion on this?

**Comment by pascalbaljet** [comment]
Thanks, I'll look into it. We use`$hasError` in the Bootstrap templates, but perhaps we could use the `@errors` directive there as well.

**Comment by pascalbaljet** [comment]
We could depend on the `Illuminate\View\Middleware\ShareErrorsFromSession` middleware and assume the errors are shared with the view instances. This is how Livewire updates the errors as well.

**Comment by pascalbaljet** [comment]
I just tagged v1.2.0 with support for Livewire:
https://github.com/pascalbaljetmedia/laravel-form-components#laravel-livewire

**Comment by dennisvandalen** [comment]
Wow, awesome! Thanks @pascalbaljet 🎉
