### ISSUE TITLE
Passing parameters to getBoundTarget method

### ISSUE THREAD

**Issue by ricazao** [pascalbaljetmedia/laravel-form-components#4]
Hi @pascalbaljet, great work!

Please check this line:

https://github.com/pascalbaljetmedia/laravel-form-components/blob/f7c12a464e216cde42f439be5eed73a07e283245/src/Components/HandlesDefaultAndOldValue.php#L25

You are passing two parameters to `getBoundTarget()` method.

**Comment by pascalbaljet** [comment]
Thanks for noticing! I’ll update it soon.

**Comment by pascalbaljet** [comment]
Fixed in v1.2.1 (#5)
